"""initial_schema

Revision ID: 092be546f82c
Revises: 
Create Date: 2026-05-25 23:32:22.347631

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '092be546f82c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rollup_date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('outreach_sent', sa.Integer(), nullable=False),
    sa.Column('outreach_delivered', sa.Integer(), nullable=False),
    sa.Column('outreach_opened', sa.Integer(), nullable=False),
    sa.Column('outreach_replied', sa.Integer(), nullable=False),
    sa.Column('compliance_blocks', sa.Integer(), nullable=False),
    sa.Column('meetings_scheduled', sa.Integer(), nullable=False),
    sa.Column('meetings_completed', sa.Integer(), nullable=False),
    sa.Column('ai_spend_inr', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_daily_rollup_date'), 'analytics_daily', ['rollup_date'], unique=False)
    op.create_index(op.f('ix_analytics_daily_tenant_id'), 'analytics_daily', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('recipient_hash', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('employee_count_range', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.create_table('hr_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_deliverable', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_in_evidence', sa.Text(), nullable=True),
    sa.Column('is_contactable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_contacts_company_id'), 'hr_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_hr_contacts_tenant_id'), 'hr_contacts', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meeting_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_stage'), 'leads', ['stage'], unique=False)
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_leads_workspace_id'), 'leads', ['workspace_id'], unique=False)
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cloudinary_url', sa.String(length=1000), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_contact_id'), 'proposals', ['contact_id'], unique=False)
    op.create_index(op.f('ix_proposals_tenant_id'), 'proposals', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_proposals_workspace_id'), 'proposals', ['workspace_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_post_id', sa.String(length=255), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_tenant_id'), 'social_posts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_social_posts_workspace_id'), 'social_posts', ['workspace_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_tier', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_run_limit', sa.Integer(), nullable=False),
    sa.Column('outreach_send_limit', sa.Integer(), nullable=False),
    sa.Column('ai_budget_inr', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_table('trainer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('niche', sa.String(length=500), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('pricing_min_inr', sa.Integer(), nullable=True),
    sa.Column('pricing_max_inr', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('usp', sa.Text(), nullable=True),
    sa.Column('target_industries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_profiles_tenant_id'), 'trainer_profiles', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trainer_profiles_workspace_id'), 'trainer_profiles', ['workspace_id'], unique=False)
    op.create_table('unsubscribe_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unsubscribe_list_contact_hash'), 'unsubscribe_list', ['contact_hash'], unique=False)
    op.create_index(op.f('ix_unsubscribe_list_tenant_id'), 'unsubscribe_list', ['tenant_id'], unique=False)
    op.create_table('usage_meters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('ai_runs_used', sa.Integer(), nullable=False),
    sa.Column('outreach_sends_used', sa.Integer(), nullable=False),
    sa.Column('ai_spend_inr', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_meters_subscription_id'), 'usage_meters', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_usage_meters_tenant_id'), 'usage_meters', ['tenant_id'], unique=False)
    op.create_table('whatsapp_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('window_opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_sessions_contact_id'), 'whatsapp_sessions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_sessions_tenant_id'), 'whatsapp_sessions', ['tenant_id'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('meta_template_id', sa.String(length=255), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_tenant_id'), 'whatsapp_templates', ['tenant_id'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_status'), 'campaign_recipients', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_tenant_id'), 'campaign_recipients', ['tenant_id'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('ab_variant', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_campaign_id'), 'outbound_messages', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_contact_id'), 'outbound_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_status'), 'outbound_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_messages_tenant_id'), 'outbound_messages', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbound_messages_tenant_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_status'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_contact_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_campaign_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_campaign_recipients_tenant_id'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_status'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_whatsapp_templates_tenant_id'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_sessions_tenant_id'), table_name='whatsapp_sessions')
    op.drop_index(op.f('ix_whatsapp_sessions_contact_id'), table_name='whatsapp_sessions')
    op.drop_table('whatsapp_sessions')
    op.drop_index(op.f('ix_usage_meters_tenant_id'), table_name='usage_meters')
    op.drop_index(op.f('ix_usage_meters_subscription_id'), table_name='usage_meters')
    op.drop_table('usage_meters')
    op.drop_index(op.f('ix_unsubscribe_list_tenant_id'), table_name='unsubscribe_list')
    op.drop_index(op.f('ix_unsubscribe_list_contact_hash'), table_name='unsubscribe_list')
    op.drop_table('unsubscribe_list')
    op.drop_index(op.f('ix_trainer_profiles_workspace_id'), table_name='trainer_profiles')
    op.drop_index(op.f('ix_trainer_profiles_tenant_id'), table_name='trainer_profiles')
    op.drop_table('trainer_profiles')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_social_posts_workspace_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_tenant_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_proposals_workspace_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_tenant_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_contact_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('orgs')
    op.drop_index(op.f('ix_leads_workspace_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_stage'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_hr_contacts_tenant_id'), table_name='hr_contacts')
    op.drop_index(op.f('ix_hr_contacts_company_id'), table_name='hr_contacts')
    op.drop_table('hr_contacts')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_analytics_daily_tenant_id'), table_name='analytics_daily')
    op.drop_index(op.f('ix_analytics_daily_rollup_date'), table_name='analytics_daily')
    op.drop_table('analytics_daily')
    # ### end Alembic commands ###
