"""add_model_runs_table

Revision ID: 2085253d0300
Revises: 092be546f82c
Create Date: 2026-05-26 17:02:28.760003

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2085253d0300'
down_revision: Union[str, None] = '092be546f82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=False),
    sa.Column('prompt_name', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_inr', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('agent', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Org-level tenant isolation key — must match app.tenant_id in RLS'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_created_at'), 'model_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_runs_model'), 'model_runs', ['model'], unique=False)
    op.create_index(op.f('ix_model_runs_request_id'), 'model_runs', ['request_id'], unique=False)
    op.create_index(op.f('ix_model_runs_run_id'), 'model_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_model_runs_task'), 'model_runs', ['task'], unique=False)
    op.create_index(op.f('ix_model_runs_tenant_id'), 'model_runs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_runs_tenant_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_task'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_run_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_request_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_model'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_created_at'), table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
