"""Sprint 29 — add business_tasks table (Business Operations Center).

Revision ID: a4c9e2f7b1d5
Revises: e2a9f4c7b1d8
Create Date: 2026-06-27

EXPAND-ONLY migration (no destructive changes to existing tables).

Creates:
  business_tasks
    Human-work tasks for the Business Operations Center.  Tasks are created
    manually or by explicit trainer action — never auto-generated by background
    jobs or AI.

    source_type / source_id: optional back-reference to the originating entity
    (crm, campaign, proposal, recommendation, manual).

    status lifecycle:
      backlog → in_progress → completed
                             ↘ blocked (can continue or be cancelled)
      Any status can be soft-deleted (status = 'deleted').

    completed_at is set by the service layer when status transitions to
    'completed'; never set directly via migration default.

    created_by stores the user_id (UUID as string) of the JWT-authenticated
    trainer who created the task.

RLS: same tenant_isolation pattern as all business tables.
Reversible: downgrade drops the table and its policy.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql as pg


revision = "a4c9e2f7b1d5"
down_revision = "e2a9f4c7b1d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "business_tasks",
        sa.Column("id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("tenant_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("workspace_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("source_type", sa.String(64), nullable=True),
        sa.Column("source_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("priority", sa.String(16), nullable=False, server_default="medium"),
        sa.Column("status", sa.String(32), nullable=False, server_default="backlog"),
        sa.Column("assignee", sa.String(256), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(256), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Composite indexes for all hot query patterns
    op.create_index(
        "ix_business_tasks_workspace",
        "business_tasks",
        ["tenant_id", "workspace_id"],
    )
    op.create_index(
        "ix_business_tasks_status",
        "business_tasks",
        ["tenant_id", "workspace_id", "status"],
    )
    op.create_index(
        "ix_business_tasks_priority",
        "business_tasks",
        ["tenant_id", "workspace_id", "priority"],
    )
    op.create_index(
        "ix_business_tasks_due_date",
        "business_tasks",
        ["tenant_id", "workspace_id", "due_date"],
    )
    op.execute("ALTER TABLE business_tasks ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE business_tasks FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY business_tasks_tenant_isolation
          ON business_tasks
          USING (tenant_id = current_setting('app.tenant_id')::uuid)
        """
    )


def downgrade() -> None:
    op.execute(
        "DROP POLICY IF EXISTS business_tasks_tenant_isolation ON business_tasks"
    )
    op.drop_index("ix_business_tasks_due_date", table_name="business_tasks")
    op.drop_index("ix_business_tasks_priority", table_name="business_tasks")
    op.drop_index("ix_business_tasks_status", table_name="business_tasks")
    op.drop_index("ix_business_tasks_workspace", table_name="business_tasks")
    op.drop_table("business_tasks")
