"""Sprint 14 — expand workspace + lead for booking webhook (ADR-0009).

Revision ID: d4e2f7a8b3c1
Revises: f1a8e5d3c2b9
Create Date: 2026-06-17

EXPAND step only (ADR-0006).  Both columns are nullable with no tightened
NOT NULL constraints.

Adds:
  workspaces.booking_webhook_secret  VARCHAR(255) NULL
    — Per-workspace HMAC-SHA256 shared secret.  Generated by the API on first
      regenerate request.  Stored as plaintext (protected by Postgres TDE at
      rest; accessible only to authenticated org admins via the identity API).
      NULL means the trainer has not yet configured a booking webhook.

  leads.booking_provider_event_id  VARCHAR(255) NULL
    — The external event ID from the booking provider that set
      meeting_scheduled_at via the webhook.  NULL for manually-entered times.
      Allows round-trip correlation between our CRM and the provider's event.
      Not a FK — the FK lives in booking_webhook_events.lead_id.

No RLS changes: workspaces uses Base (no RLS); leads already has RLS from
the initial schema.  Adding a nullable column does not affect existing policies.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "d4e2f7a8b3c1"
down_revision = "f1a8e5d3c2b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "workspaces",
        sa.Column("booking_webhook_secret", sa.String(255), nullable=True),
    )
    op.add_column(
        "leads",
        sa.Column("booking_provider_event_id", sa.String(255), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("leads", "booking_provider_event_id")
    op.drop_column("workspaces", "booking_webhook_secret")
